services:
  redis:
    extends:
      file: ./docker-compose.base.yml
      service: redis

  llm:
    build:
      context: .
      dockerfile: LLM/Dockerfile
      network: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    extends:
      file: ./docker-compose.base.yml
      service: llm
    ports:
      - '8547:8547'

networks:
  uptime:
    driver: bridge
