networks:
    uptime:
        driver: bridge

services:
    accounts:
        image: ${IMAGE_PREFIX}/uptime/accounts:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: accounts
        networks:
            - uptime

    admin-dashboard:
        image: ${IMAGE_PREFIX}/uptime/admin-dashboard:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: admin-dashboard
        networks:
            - uptime

    api-reference:
        image: ${IMAGE_PREFIX}/uptime/api-reference:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: api-reference
        networks:
            - uptime

    app:
        image: ${IMAGE_PREFIX}/uptime/app:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: app
        networks:
            - uptime

    clickhouse:
        image: 401376717990.dkr.ecr.us-east-1.amazonaws.com/docker-hub/clickhouse/clickhouse-server:23.7
        # image: ${IMAGE_PREFIX}/docker-hub/clickhouse/clickhouse-server:23.7
        extends:
            file: ./docker-compose.build.yml
            service: clickhouse
        networks:
            - uptime

    copilot:
        image: ${IMAGE_PREFIX}/uptime/copilot:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: copilot
        networks:
            - uptime

    dashboard:
        image: ${IMAGE_PREFIX}/uptime/dashboard:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: dashboard
        networks:
            - uptime

    docs:
        image: ${IMAGE_PREFIX}/uptime/docs:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: docs
        networks:
            - uptime

    e2e:
        image: ${IMAGE_PREFIX}/uptime/e2e:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: e2e
        network_mode: host

    fluentd:
        image: ${IMAGE_PREFIX}/uptime/fluentd:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: fluentd
        networks:
            - uptime

    haraka:
        image: ${IMAGE_PREFIX}/uptime/haraka:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: haraka
        networks:
            - uptime

    home:
        image: ${IMAGE_PREFIX}/uptime/home:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: home
        networks:
            - uptime

    ingestor:
        image: ${IMAGE_PREFIX}/uptime/ingestor:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: ingestor
        networks:
            - uptime

    isolated-vm:
        image: ${IMAGE_PREFIX}/uptime/isolated-vm:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: isolated-vm
        networks:
            - uptime

    monitor:
        image: ${IMAGE_PREFIX}/uptime/monitor:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: monitor
        networks:
            - uptime

    nginx:
        image: ${IMAGE_PREFIX}/uptime/nginx:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: nginx
        networks:
            - uptime

    otel-collector:
        image: ${IMAGE_PREFIX}/uptime/otel-collector:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: otel-collector
        networks:
            - uptime

    postgres:
        ports:
            - "5400:5432" # for access to postgres for backups. If you don't need backup, you can comment this line out to make it more secure.
        extends:
            file: ./docker-compose.build.yml
            service: postgres
        networks:
            - uptime

    probe-1:
        image: ${IMAGE_PREFIX}/uptime/probe:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: probe-1
        networks:
            - uptime

    probe-2:
        image: ${IMAGE_PREFIX}/uptime/probe:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: probe-2
        networks:
            - uptime

    redis:
        image: ${IMAGE_PREFIX}/docker-hub/library/redis:7.0.12
        extends:
            file: ./docker-compose.build.yml
            service: redis
        ports:
            - '6310:6379'
        networks:
            - uptime

    status-page:
        image: ${IMAGE_PREFIX}/uptime/status-page:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: status-page
        networks:
            - uptime

    test-server:
        image: ${IMAGE_PREFIX}/uptime/test-server:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: test-server
        networks:
            - uptime

    worker:
        image: ${IMAGE_PREFIX}/uptime/worker:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: worker
        networks:
            - uptime

    workflow:
        image: ${IMAGE_PREFIX}/uptime/workflow:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: workflow
        networks:
            - uptime

volumes:
    postgres:
    clickhouse:
