services:


  admin-dashboard:
    extends:
      file: ./docker-compose.base.yml
      service: admin-dashboard
    build:
      context: .
      dockerfile: AdminDashboard/Dockerfile
    ports:
      - '${ADMIN_DASHBOARD_PORT}:${ADMIN_DASHBOARD_PORT}'
      - '9230:9229' # Debug port
    volumes:
      - ./AdminDashboard:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

    redis:
        ports:
            - '6310:6379'
        extends:
            file: ./docker-compose.base.yml
            service: redis

    clickhouse:
        ports:
            - '9034:9000'
            - '8189:8123'
        extends:
            file: ./docker-compose.base.yml
            service: clickhouse

    postgres:
        ports:
            - '5400:5432'
        extends:
            file: ./docker-compose.base.yml
            service: postgres

  # copilot:
  #   extends:
  #     file: ./docker-compose.base.yml
  #     service: copilot
  #   build:
  #     context: .
  #     dockerfile: Copilot/Dockerfile
  #   ports:
  #     - '${COPILOT_PORT}:${COPILOT_PORT}'
  #     - '9985:9229' # Debug port
  #   volumes:
  #     - ./Copilot:/usr/src/app
  #     - /usr/src/app/node_modules/
  #     - ./Common:/usr/src/Common
  #     - /usr/src/Common/node_modules/

  dashboard:
    extends:
      file: ./docker-compose.base.yml
      service: dashboard
    build:
      context: .
      dockerfile: Dashboard/Dockerfile
    ports:
      - '${DASHBOARD_PORT}:${DASHBOARD_PORT}'
      - '9233:9229' # Debug port
    volumes:
      - ./Dashboard:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

    accounts:
        ports:
            - '${ACCOUNTS_PORT}:${ACCOUNTS_PORT}' # ws port for webpack
        extends:
            file: ./docker-compose.base.yml
            service: accounts
        volumes:
            - ./Accounts:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/dev-env
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common

  e2e:
    extends:
      file: ./docker-compose.base.yml
      service: e2e
    build:
      context: .
      dockerfile: E2E/Dockerfile
    volumes:
      - ./E2E/playwright-report:/usr/src/app/playwright-report
      - ./E2E/test-results:/usr/src/app/test-results


        build:
            network: host
            context: .
            dockerfile: ./Accounts/Dockerfile


    dashboard:
        ports:
            - '${DASHBOARD_PORT}:${DASHBOARD_PORT}' # ws port for webpack
        extends:
            file: ./docker-compose.base.yml
            service: dashboard
        volumes:
            - ./Dashboard:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/dev-env
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common

  home:
    extends:
      file: ./docker-compose.base.yml
      service: home
    build:
      context: .
      dockerfile: Home/Dockerfile
    ports:
      - '${HOME_PORT}:${HOME_PORT}'
      - '9212:9229' # Debug port
    volumes:
      - ./Home:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/


        build:
            network: host
            context: .
            dockerfile: ./Dashboard/Dockerfile



    admin-dashboard:
        ports:
            - '${ADMIN_DASHBOARD_PORT}:${ADMIN_DASHBOARD_PORT}' # ws port for webpack
        extends:
            file: ./docker-compose.base.yml
            service: admin-dashboard
        volumes:
            - ./AdminDashboard:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/dev-env
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common

  # llm:
  #   extends:
  #     file: ./docker-compose.base.yml
  #     service: llm
  #   build:
  #     context: .
  #     dockerfile: LLM/Dockerfile
  #   ports:
  #     - '${LLM_PORT}:${LLM_PORT}'


        build:
            network: host
            context: .
            dockerfile: ./AdminDashboard/Dockerfile

  nginx:
    extends:
      file: ./docker-compose.base.yml
      service: nginx
    build:
      context: .
      dockerfile: Nginx/Dockerfile
    # ports:
    #   - '${NGINX_PORT}:${NGINX_PORT}'

    status-page:
        ports:
            - '${STATUS_PAGE_PORT}:${STATUS_PAGE_PORT}' # ws port for webpack
        extends:
            file: ./docker-compose.base.yml
            service: status-page
        volumes:
            - ./StatusPage:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/dev-env
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common

  postgres:
    extends:
      file: ./docker-compose.base.yml
      service: postgres
    ports:
      - '5400:5432'


        build:
            network: host
            context: .
            dockerfile: ./StatusPage/Dockerfile


    test-server:
        volumes:
            - ./TestServer:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common

  probe-2:
    extends:
      file: ./docker-compose.base.yml
      service: probe-2
    build:
      context: .
      dockerfile: Probe/Dockerfile
    ports:
      - '${PROBE_2_PORT}:${PROBE_2_PORT}'
      - '9656:9229' # Debug port
    volumes:
      - ./Probe:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/


        extends:
            file: ./docker-compose.base.yml
            service: test-server
        ports:
            - '9141:9229' # Debugging port.
            - '3800:3800'
        build:
            network: host
            context: .
            dockerfile: ./TestServer/Dockerfile

  status-page:
    extends:
      file: ./docker-compose.base.yml
      service: status-page
    build:
      context: .
      dockerfile: StatusPage/Dockerfile
    ports:
      - '${STATUS_PAGE_PORT}:${STATUS_PAGE_PORT}' # ws port for webpack
      - '9234:9229' # Debug port
    volumes:
      - ./StatusPage:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  test-server:
    extends:
      file: ./docker-compose.base.yml
      service: test-server
    build:
      context: .
      dockerfile: TestServer/Dockerfile
    ports:
      - '${TEST_SERVER_PORT}:${TEST_SERVER_PORT}'
      - '9141:9229' # Debug port
      - '3800:3800'
    volumes:
      - ./TestServer:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  worker:
    extends:
      file: ./docker-compose.base.yml
      service: worker
    build:
      context: .
      dockerfile: Worker/Dockerfile
    ports:
      - '${WORKER_PORT}:${WORKER_PORT}'
      - '8734:9229' # Debug port
    volumes:
      - ./Worker:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/


    workflow:
        volumes:
            - ./Workflow:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common
            - /usr/src/Common/node_modules/
        extends:
            file: ./docker-compose.base.yml
            service: workflow
        ports:
            - '8735:9229' # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./Workflow/Dockerfile

    api-reference:
        volumes:
            - ./APIReference:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common
            - /usr/src/Common/node_modules/
        extends:
            file: ./docker-compose.base.yml
            service: api-reference
        ports:
            - '8737:9229' # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./APIReference/Dockerfile

    docs:
        volumes:
            - ./Docs:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common
            - /usr/src/Common/node_modules/
        extends:
            file: ./docker-compose.base.yml
            service: docs
        ports:
            - '8738:9229' # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./Docs/Dockerfile

    app:
        volumes:
            - ./App:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common
            - /usr/src/Common/node_modules/
        extends:
            file: ./docker-compose.base.yml
            service: app
        ports:
            - '9232:9229' # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./App/Dockerfile


    probe-1:
        volumes:
            - ./Probe:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common

            - /usr/src/Common/node_modules/


        extends:
            file: ./docker-compose.base.yml
            service: probe-1
        ports:
          - '9655:9229' # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./Probe/Dockerfile

    probe-2:
        volumes:
            - ./Probe:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common

            - /usr/src/Common/node_modules/


        extends:
            file: ./docker-compose.base.yml
            service: probe-2
        ports:
          - '9656:9229' # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./Probe/Dockerfile

    isolated-vm:
        volumes:
            - ./IsolatedVM:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common

            - /usr/src/Common/node_modules/


        ports:
          - '9974:9229' # Debugging port.
        extends:
            file: ./docker-compose.base.yml
            service: isolated-vm
        build:
            network: host
            context: .
            dockerfile: ./IsolatedVM/Dockerfile

    ingestor:
        volumes:
            - ./Ingestor:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common

            - /usr/src/Common/node_modules/


        ports:
          - '9932:9229' # Debugging port.
        extends:
            file: ./docker-compose.base.yml
            service: ingestor
        build:
            network: host
            context: .
            dockerfile: ./Ingestor/Dockerfile


    # Fluentd. Required only for development. In  production its the responsibility of the customer to run fluentd and pipe logs to OneUptime.
    # We run this container just for development, to see if logs are piped.

    fluentd:
        ports:
            - 24224:24224
            - 24224:24224/udp
        user: fluent
        extends:
            file: ./docker-compose.base.yml
            service: fluentd
        volumes:
            - ./Fluentd/fluent.conf:/fluentd/etc/fluent.conf
        build:
            network: host
            context: ./Fluentd
            dockerfile: ./Dockerfile

    ingress:
        build:
            network: host
            context: .
            dockerfile: ./Nginx/Dockerfile
        extends:
            file: ./docker-compose.base.yml
            service: ingress

    # e2e tests
    e2e:
        extends:
            file: ./docker-compose.base.yml
            service: e2e
        volumes:
            - ./E2E/playwright-report:/usr/src/app/playwright-report
            - ./E2E/test-results:/usr/src/app/test-results
        build:
            network: host
            context: .
            dockerfile: ./E2E/Dockerfile

    copilot:
        volumes:
            - ./Copilot:/usr/src/app
            # Use node modules of the container and not host system.
            # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
            - /usr/src/app/node_modules/
            - ./Common:/usr/src/Common
            - /usr/src/Common/node_modules/
        ports:
            - '9985:9229' # Debugging port.
        extends:
            file: ./docker-compose.base.yml
            service: copilot
        build:
            network: host
            context: .
            dockerfile: ./Copilot/Dockerfile

volumes:
    postgres:
    clickhouse:

networks:
  uptime:
    driver: bridge
