services:
  accounts:
    extends:
      file: ./docker-compose.base.yml
      service: accounts
    build:
      context: .
      dockerfile: ./Accounts/Dockerfile
    ports:
      - '${ACCOUNTS_PORT}:${ACCOUNTS_PORT}'
      - '9229:9229' # Debug port
    volumes:
      - ./Accounts:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  admin-dashboard:
    extends:
      file: ./docker-compose.base.yml
      service: admin-dashboard
    build:
      context: .
      dockerfile: AdminDashboard/Dockerfile
    ports:
      - '${ADMIN_DASHBOARD_PORT}:${ADMIN_DASHBOARD_PORT}'
      - '9230:9229' # Debug port
    volumes:
      - ./AdminDashboard:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  api-reference:
    extends:
      file: ./docker-compose.base.yml
      service: api-reference
    build:
      context: .
      dockerfile: APIReference/Dockerfile
    ports:
      - '${API_REFERENCE_PORT}:${API_REFERENCE_PORT}'
      - '8737:9229' # Debug port
    volumes:
      - ./APIReference:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  app:
    extends:
      file: ./docker-compose.base.yml
      service: app
    build:
      context: .
      dockerfile: App/Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '9232:9229' # Debug port
    volumes:
      - ./App:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  clickhouse:
    extends:
      file: ./docker-compose.base.yml
      service: clickhouse
    ports:
      - '9034:9000'
      - '8189:8123'

  copilot:
    extends:
      file: ./docker-compose.base.yml
      service: copilot
    build:
      context: .
      dockerfile: Copilot/Dockerfile
    ports:
      - '${COPILOT_PORT}:${COPILOT_PORT}'
      - '9985:9229' # Debug port
    volumes:
      - ./Copilot:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  dashboard:
    extends:
      file: ./docker-compose.base.yml
      service: dashboard
    build:
      context: .
      dockerfile: Dashboard/Dockerfile
    ports:
      - '${DASHBOARD_PORT}:${DASHBOARD_PORT}'
      - '9233:9229' # Debug port
    volumes:
      - ./Dashboard:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  docs:
    extends:
      file: ./docker-compose.base.yml
      service: docs
    build:
      context: .
      dockerfile: Docs/Dockerfile
    ports:
      - '${DOCS_PORT}:${DOCS_PORT}'
      - '8738:9229' # Debug port
    volumes:
      - ./Docs:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  e2e:
    extends:
      file: ./docker-compose.base.yml
      service: e2e
    build:
      context: .
      dockerfile: E2E/Dockerfile
    volumes:
      - ./E2E/playwright-report:/usr/src/app/playwright-report
      - ./E2E/test-results:/usr/src/app/test-results

  fluentd:
    extends:
      file: ./docker-compose.base.yml
      service: fluentd
    build:
      context: .
      dockerfile: Fluentd/Dockerfile
    ports:
      - '24224:24224'
      - '24224:24224/udp'
      - '8888:8888'
    volumes:
      - ./Fluentd/fluent.conf:/fluentd/etc/fluent.conf

  haraka:
    extends:
      file: ./docker-compose.base.yml
      service: haraka
    build:
      context: .
      dockerfile: Haraka/Dockerfile
    ports:
      - '${HARAKA_PORT}:${HARAKA_PORT}'

  home:
    extends:
      file: ./docker-compose.base.yml
      service: home
    build:
      context: .
      dockerfile: Home/Dockerfile
    ports:
      - '${HOME_PORT}:${HOME_PORT}'
      - '9212:9229' # Debug port
    volumes:
      - ./Home:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  ingestor:
    extends:
      file: ./docker-compose.base.yml
      service: ingestor
    build:
      context: .
      dockerfile: Ingestor/Dockerfile
    ports:
      - '${INGESTOR_PORT}:${INGESTOR_PORT}'
      - '9932:9229' # Debug port
    volumes:
      - ./Ingestor:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  isolated-vm:
    extends:
      file: ./docker-compose.base.yml
      service: isolated-vm
    build:
      context: .
      dockerfile: IsolatedVM/Dockerfile
    ports:
      - '${ISOLATED_VM_PORT}:${ISOLATED_VM_PORT}'
      - '9974:9229' # Debug port
    volumes:
      - ./IsolatedVM:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  llm:
    extends:
      file: ./docker-compose.base.yml
      service: llm
    build:
      context: .
      dockerfile: LLM/Dockerfile
    ports:
      - '${LLM_PORT}:${LLM_PORT}'

  monitor:
    extends:
      file: ./docker-compose.base.yml
      service: monitor
    build:
      context: .
      dockerfile: Monitor/Dockerfile
    ports:
      - '4010:4010'
    volumes:
      - ./Monitor:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  nginx:
    extends:
      file: ./docker-compose.base.yml
      service: nginx
    build:
      context: .
      dockerfile: Nginx/Dockerfile
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'

  otel-collector:
    extends:
      file: ./docker-compose.base.yml
      service: otel-collector
    build:
      context: .
      dockerfile: OTelCollector/Dockerfile
    ports:
      - '${OTEL_COLLECTOR_PORT}:${OTEL_COLLECTOR_PORT}'

  postgres:
    extends:
      file: ./docker-compose.base.yml
      service: postgres
    ports:
      - '5400:5432'

  probe-1:
    extends:
      file: ./docker-compose.base.yml
      service: probe-1
    build:
      context: .
      dockerfile: Probe/Dockerfile
    ports:
      - '${PROBE_1_PORT}:${PROBE_1_PORT}'
      - '9655:9229' # Debug port
    volumes:
      - ./Probe:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  probe-2:
    extends:
      file: ./docker-compose.base.yml
      service: probe-2
    build:
      context: .
      dockerfile: Probe/Dockerfile
    ports:
      - '${PROBE_2_PORT}:${PROBE_2_PORT}'
      - '9656:9229' # Debug port
    volumes:
      - ./Probe:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  redis:
    extends:
      file: ./docker-compose.base.yml
      service: redis
    ports:
      - '6310:6379'

  status-page:
    extends:
      file: ./docker-compose.base.yml
      service: status-page
    build:
      context: .
      dockerfile: StatusPage/Dockerfile
    ports:
      - '${STATUS_PAGE_PORT}:${STATUS_PAGE_PORT}' # ws port for webpack
      - '9234:9229' # Debug port
    volumes:
      - ./StatusPage:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  test-server:
    extends:
      file: ./docker-compose.base.yml
      service: test-server
    build:
      context: .
      dockerfile: TestServer/Dockerfile
    ports:
      - '${TEST_SERVER_PORT}:${TEST_SERVER_PORT}'
      - '9141:9229' # Debug port
      - '3800:3800'
    volumes:
      - ./TestServer:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  worker:
    extends:
      file: ./docker-compose.base.yml
      service: worker
    build:
      context: .
      dockerfile: Worker/Dockerfile
    ports:
      - '${WORKER_PORT}:${WORKER_PORT}'
      - '8734:9229' # Debug port
    volumes:
      - ./Worker:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  workflow:
    extends:
      file: ./docker-compose.base.yml
      service: workflow
    build:
      context: .
      dockerfile: Workflow/Dockerfile
    ports:
      - '${WORKFLOW_PORT}:${WORKFLOW_PORT}'
      - '8735:9229' # Debug port
    volumes:
      - ./Workflow:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

volumes:
  postgres:
  clickhouse:

networks:
  uptime:
    driver: bridge
