services:
    accounts:
        image: ${IMAGE_PREFIX}/accounts:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: accounts

    admin-dashboard:
        image: ${IMAGE_PREFIX}/admin-dashboard:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: admin-dashboard

    api-reference:
        image: ${IMAGE_PREFIX}/api-reference:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: api-reference

    app:
        image: ${IMAGE_PREFIX}/app:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: app

    clickhouse:
        image: ${IMAGE_PREFIX}/clickhouse:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: clickhouse

    copilot:
        image: ${IMAGE_PREFIX}/copilot:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: copilot

    dashboard:
        image: ${IMAGE_PREFIX}/dashboard:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: dashboard

    docs:
        image: ${IMAGE_PREFIX}/docs:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: docs

    e2e:
        image: ${IMAGE_PREFIX}/e2e:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: e2e

    fluentd:
        image: ${IMAGE_PREFIX}/fluentd:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: fluentd

    haraka:
        image: ${IMAGE_PREFIX}/haraka:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: haraka

    home:
        image: ${IMAGE_PREFIX}/home:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: home

    ingestor:
        image: ${IMAGE_PREFIX}/ingestor:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: ingestor

    isolated-vm:
        image: ${IMAGE_PREFIX}/isolated-vm:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: isolated-vm

    monitor:
        image: ${IMAGE_PREFIX}/monitor:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: monitor

    llm:
        image: ${IMAGE_PREFIX}/llm:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: llm

    nginx:
        image: ${IMAGE_PREFIX}/nginx:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: nginx

    otel-collector:
        image: ${IMAGE_PREFIX}/otel-collector:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: otel-collector

    postgres:
        ports:
            - "5400:5432" # for access to postgres for backups. If you don't need backup, you can comment this line out to make it more secure.
        extends:
            file: ./docker-compose.build.yml
            service: postgres

    probe-1:
        image: ${IMAGE_PREFIX}/probe:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: probe-1

    probe-2:
        image: ${IMAGE_PREFIX}/probe:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: probe-2

    redis:
        image: ${IMAGE_PREFIX}/redis:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: redis

    status-page:
        image: ${IMAGE_PREFIX}/status-page:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: status-page

    test-server:
        image: ${IMAGE_PREFIX}/test-server:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: test-server

    worker:
        image: ${IMAGE_PREFIX}/worker:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: worker

    workflow:
        image: ${IMAGE_PREFIX}/workflow:${APP_TAG}
        extends:
            file: ./docker-compose.build.yml
            service: workflow

volumes:
    postgres:
    clickhouse:

networks:
    uptime:
        driver: bridge
