services:
  accounts:
    extends:
      file: ./docker-compose.base.yml
      service: accounts
    build:
      network: host
      context: .
      dockerfile: ./Accounts/Dockerfile
    ports:
      - '${ACCOUNTS_PORT}:${ACCOUNTS_PORT}' # ws port for webpack
    volumes:
      - ./Accounts:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  admin-dashboard:
    extends:
      file: ./docker-compose.base.yml
      service: admin-dashboard
    build:
      network: host
      context: .
      dockerfile: AdminDashboard/Dockerfile
    volumes:
      - ./AdminDashboard:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  api-reference:
    extends:
      file: ./docker-compose.base.yml
      service: api-reference
    build:
      network: host
      context: .
      dockerfile: APIReference/Dockerfile
    ports:
      - '8737:9229' # Debugging port.
    volumes:
      - ./APIReference:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  app:
    extends:
      file: ./docker-compose.base.yml
      service: app
    build:
      network: host
      context: .
      dockerfile: App/Dockerfile
    ports:
      - '9232:9229' # Debugging port.
    volumes:
      - ./App:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  clickhouse:
    extends:
      file: ./docker-compose.base.yml
      service: clickhouse
    ports:
      - '9034:9000'
      - '8189:8123'

  copilot:
    extends:
      file: ./docker-compose.base.yml
      service: copilot
    build:
      network: host
      context: .
      dockerfile: Copilot/Dockerfile
    ports:
      - '9985:9229' # Debugging port.
    volumes:
      - ./Copilot:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  dashboard:
    extends:
      file: ./docker-compose.base.yml
      service: dashboard
    build:
      network: host
      context: .
      dockerfile: Dashboard/Dockerfile
    volumes:
      - ./Dashboard:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  docs:
    extends:
      file: ./docker-compose.base.yml
      service: docs
    build:
      network: host
      context: .
      dockerfile: Docs/Dockerfile
    ports:
      - '8738:9229' # Debugging port.
    volumes:
      - ./Docs:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  e2e:
    extends:
      file: ./docker-compose.base.yml
      service: e2e
    build:
      network: host
      context: .
      dockerfile: E2E/Dockerfile
    volumes:
      - ./E2E/playwright-report:/usr/src/app/playwright-report
      - ./E2E/test-results:/usr/src/app/test-results

  fluentd:
    extends:
      file: ./docker-compose.base.yml
      service: fluentd
    build:
      network: host
      context: .
      dockerfile: Fluentd/Dockerfile
    ports:
      - 24224:24224
      - 24224:24224/udp
      - 8888:8888
    volumes:
      - ./Fluentd/fluent.conf:/fluentd/etc/fluent.conf

  haraka:
    extends:
      file: ./docker-compose.base.yml
      service: haraka
    build:
      network: host
      context: .
      dockerfile: Haraka/Dockerfile

  home:
    extends:
      file: ./docker-compose.base.yml
      service: home
    build:
      network: host
      context: .
      dockerfile: Home/Dockerfile
    ports:
      - '9212:9229' # Debugging port.
    volumes:
      - ./Home:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  ingestor:
    extends:
      file: ./docker-compose.base.yml
      service: ingestor
    build:
      network: host
      context: .
      dockerfile: Ingestor/Dockerfile
    ports:
      - '9932:9229' # Debugging port.
    volumes:
      - ./Ingestor:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  isolated-vm:
    extends:
      file: ./docker-compose.base.yml
      service: isolated-vm
    build:
      network: host
      context: .
      dockerfile: IsolatedVM/Dockerfile
    ports:
      - '9974:9229' # Debugging port.
    volumes:
      - ./IsolatedVM:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  llm:
    extends:
      file: ./docker-compose.base.yml
      service: llm
    build:
      network: host
      context: .
      dockerfile: LLM/Dockerfile

  monitor:
    extends:
      file: ./docker-compose.base.yml
      service: monitor
    build:
      network: host
      context: .
      dockerfile: Monitor/Dockerfile
    ports:
      - '3010:3010' # Debugging port.
    volumes:
      - ./Monitor:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  nginx:
    extends:
      file: ./docker-compose.base.yml
      service: nginx
    build:
      network: host
      context: .
      dockerfile: Nginx/Dockerfile

  otel-collector:
    extends:
      file: ./docker-compose.base.yml
      service: otel-collector
    build:
      network: host
      context: .
      dockerfile: OTelCollector/Dockerfile

  postgres:
    ports:
      - '5400:5432'
    extends:
      file: ./docker-compose.base.yml
      service: postgres

  probe-1:
    extends:
      file: ./docker-compose.base.yml
      service: probe-1
    build:
      network: host
      context: .
      dockerfile: Probe/Dockerfile
    ports:
      - '9655:9229' # Debugging port.
    volumes:
      - ./Probe:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  probe-2:
    extends:
      file: ./docker-compose.base.yml
      service: probe-2
    build:
      network: host
      context: .
      dockerfile: Probe/Dockerfile
    ports:
      - '9656:9229' # Debugging port.
    volumes:
      - ./Probe:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  redis:
    ports:
      - '6310:6379'
    extends:
      file: ./docker-compose.base.yml
      service: redis

  status-page:
    extends:
      file: ./docker-compose.base.yml
      service: status-page
    build:
      network: host
      context: .
      dockerfile: StatusPage/Dockerfile
    ports:
      - '${STATUS_PAGE_PORT}:${STATUS_PAGE_PORT}' # ws port for webpack
    volumes:
      - ./StatusPage:/usr/src/app
      - /usr/src/app/dev-env
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  test-server:
    extends:
      file: ./docker-compose.base.yml
      service: test-server
    build:
      network: host
      context: .
      dockerfile: TestServer/Dockerfile
    ports:
      - '9141:9229' # Debugging port.
      - '3800:3800'
    volumes:
      - ./TestServer:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  worker:
    extends:
      file: ./docker-compose.base.yml
      service: worker
    build:
      network: host
      context: .
      dockerfile: Worker/Dockerfile
    ports:
      - '8734:9229' # Debugging port.
    volumes:
      - ./Worker:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

  workflow:
    extends:
      file: ./docker-compose.base.yml
      service: workflow
    build:
      network: host
      context: .
      dockerfile: Workflow/Dockerfile
    ports:
      - '8735:9229' # Debugging port.
    volumes:
      - ./Workflow:/usr/src/app
      - /usr/src/app/node_modules/
      - ./Common:/usr/src/Common
      - /usr/src/Common/node_modules/

volumes:
  postgres:
  clickhouse:

networks:
  uptime:
    driver: bridge
