name: Common Jobs

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   # excludes hotfix branches
      - 'release'

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Lint Helm Chart 
        run: |
          helm lint ./HelmChart/Public/oneuptime
          
  js-lint:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y curl gcc
      - run: sudo apt-get install -y build-essential
      - run: sudo apt-get install -y nodejs
      - run: npm install
      - run: npm run lint
      - name: Show how to fix lint
        if: ${{ failure() }}
        run: echo "Please run `npm run fix` in your root directory to fix the lint automatically."