# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
name: "CBSUptime Reliability Copilot"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest

    steps:

    # Run Reliability Copilot in Docker Container
    - name: Run Copilot
      run: |
        docker run --rm \
          -e ONEUPTIME_URL="https://test.uptime.cbsretail.net" \
          -e ONEUPTIME_REPOSITORY_SECRET_KEY="${{ secrets.COPILOT_ONEUPTIME_REPOSITORY_SECRET_KEY }}" \
          -e CODE_REPOSITORY_PASSWORD="${{ github.token }}" \
          -e CODE_REPOSITORY_USERNAME="simlarsen" \
          -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
          --net=host oneuptime/copilot:test
